// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel dripTextureDraw
#pragma kernel dripMov
#include "noiseSimplex.cginc"

struct dripPos
{
    int2 pos;
    int2 vel;
    float life;
    float lifeSave;
};

float hash11(float p)
{
    p = frac(p * 0.1031);
    p *= p + 33.33;
    p *= p + p;
    p = frac(p);
	//p -= 0.5;
    return p;
}

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture2D<float4> drips;
RWStructuredBuffer<dripPos> dripObj;
Texture2D<float4> nMapReset;
RWTexture2D<float4> nMap;

float dtd;

int dripCount;

int texRes;

[numthreads(1, 1, 1)]
void dripMov(uint3 id : SV_DispatchThreadID)
{
    float2 startNoise = float2(id.x, dtd * 2);
    float noise = snoise(startNoise);
    float noiseRound = round(noise * 0.75);
    dripObj[id.x].pos += int2(dripObj[id.x].vel.x, noiseRound);
    dripObj[id.x].pos %= texRes;
    dripObj[id.x].life -= 0.01;
    float4 col = float4(normalize(float3(0, 1, 0)), 1);
    float4 lesForwardCol = float4(normalize(float3(0, 0.5, 0)), 1);
    
    
    float xPos = dripObj[id.x].pos.x;
    if (xPos < 0.07 * texRes || xPos > 0.6875 * texRes)
    {
        dripObj[id.x].vel.x = 1;
    }
    else if (xPos > 0.25 * texRes && xPos < 0.6875 * texRes)
    {
        dripObj[id.x].vel.x = -1;
    }
    else
    {
        dripObj[id.x].life = 0;
    }
    
    if (dripObj[id.x].life > 0)
    {
        drips[dripObj[id.x].pos + float2(0, 0)] = col;
        drips[dripObj[id.x].pos + float2(0, 1)] = lesForwardCol;
        drips[dripObj[id.x].pos + float2(1, 1)] = lesForwardCol;
    }
    else
    {
        dripObj[id.x].pos.x = (int) (hash11((float) dripObj[id.x].pos.y) * texRes);
        dripObj[id.x].pos.y = (int) (hash11((float) dripObj[id.x].pos.x) * texRes);
        dripObj[id.x].life = dripObj[id.x].lifeSave;
        dripObj[id.x].lifeSave = max(0.1, hash11((float) dripObj[id.x].pos.x) * 3);

    }
    
    //float4 col = 1; //float4(1, 1, 1, 1); //((float) dripObj[id.x].pos.x / (float) texRes) ; //float4(0, 0, 0, 1);
    //float xPos = dripObj[id.x].pos.x;
    //if (xPos < 0.05 * texRes || xPos > 0.6875 * texRes)
    //{
    //    col = 0;
    //}
    //else if (xPos > 0.3 * texRes && xPos < 0.6875 * texRes)
    //{
    //    col = 0;
    //}
    ////else
    ////{
    ////    dripObj[id.x].life = 0;
    ////}
    //drips[dripObj[id.x].pos] = col;
    //drips[dripObj[id.x].pos + float2(0, 1)] = col;
    //drips[dripObj[id.x].pos + float2(1, 1)] = col;
}

[numthreads(15, 15, 1)]
void dripTextureDraw(uint3 id : SV_DispatchThreadID)
{
    nMap[id.xy] = nMapReset[id.xy];
    drips[uint2(id.x, id.y)] -= 0.02;
    drips[uint2(id.x, id.y)] = clamp(drips[uint2(id.x, id.y)], -1, 1);
    nMap[id.xy] += drips[uint2(id.x, id.y)];
}

