// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel logTex

RWTexture2D<float4> Result;
float dt;
int texRes;
static float2 stretch = float2(5,2);
#include "noiseSimplex.cginc"

[numthreads(8,8,1)]
void logTex (uint3 id : SV_DispatchThreadID)
{
    float2 pos = float2((((float2)id.xy) / (float)texRes) - 0.5);
    float noise = 1 - abs(snoise(float3(pos * stretch, dt / 20)));
    Result[id.xy] = noise ;
}
